### ISSUE TITLE
IDE Exception Short name 'ClassStringLocalInspection' is not unique class

### ISSUE THREAD

**Issue by cseufert** [Haehnchen/idea-php-generics-plugin#12] opened 2020-03-18 23:47 UTC
Hi,

I get these errors peroidically when using PHPStorm

```
com.intellij.diagnostic.PluginException: Short name 'ClassStringLocalInspection' is not unique
class 'de.espend.idea.php.generics.inspection.PsalmLocalImmutableInspection' in PluginDescriptor(name=PHP Generics, classpath=C:\Users\chris\.PhpStorm2019.3\config\plugins\PHP Generics)
and
class'de.espend.idea.php.generics.inspection.ClassStringLocalInspection' in PluginDescriptor(name=PHP Generics, classpath=C:\Users\chris\.PhpStorm2019.3\config\plugins\PHP Generics)
conflict [Plugin: de.espend.idea.php.generics]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.checkForDuplicateShortName(InspectionToolRegistrar.java:134)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.registerInspection(InspectionToolRegistrar.java:81)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.registerInspections(InspectionToolRegistrar.java:61)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.lambda$new$0(InspectionToolRegistrar.java:41)
	at com.intellij.openapi.util.NotNullLazyValue$2.compute(NotNullLazyValue.java:67)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:38)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:174)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.createTools(InspectionProfileImpl.java:459)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:481)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:110)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:476)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:110)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools$default(InspectionProfile.kt:103)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.getAllTools(InspectionProfileImpl.java:770)
	at com.intellij.ide.ui.InspectionsTopHitProvider.getOptions(InspectionsTopHitProvider.java:31)
	at com.intellij.ide.ui.OptionsTopHitProvider.getCachedOptions(OptionsTopHitProvider.java:78)
	at com.intellij.ide.ui.OptionsTopHitProvider.access$600(OptionsTopHitProvider.java:39)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.lambda$cacheAll$2(OptionsTopHitProvider.java:267)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:292)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:157)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.cacheAll(OptionsTopHitProvider.java:263)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.lambda$runActivity$0(OptionsTopHitProvider.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
using 
```
PhpStorm 2019.3.3
Build #PS-193.6494.47, built on February 13, 2020
Licensed to Chris Seufert
Subscription is active until June 2, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.github.camork.fileExpander, com.intellij.lang.jsgraphql, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, de.espend.idea.php.generics, intellij.prettierJS
```

**Comment by ArtemGoutsoul** [comment] 2020-03-22 14:23
Same thing when using
```
PhpStorm 2020.1 EAP
Build #PS-201.6487.22, built on March 19, 2020
PhpStorm EAP User
Expiration date: April 18, 2020
Runtime version: 11.0.6+8-b765.15 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 12
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.tooltip.initialDelay=187
Non-Bundled Plugins: CMD Support, Jetbrains TeamCity Plugin, Key Promoter X, Scratch, Statistic, String Manipulation, org.intellij.tasks.navigation, com.intellij.ideolog, net.seesharpsoft.intellij.plugins.csv, com.dmarcotte.handlebars, com.jetbrains.lang.ejs, ru.adelf.idea.dotenv, NEON support, lv.midiana.misc.phpstorm-plugins.deep-keys, lv.midiana.misc.idea-plugins.deep-js-completion, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, de.espend.idea.php.generics, org.psliwa.idea.composer, some.awesome
```

**Comment by suysdavid** [comment] 2020-03-25 12:58
This is probably a duplicate of #10

**Comment by Haehnchen** [comment] 2020-05-01 13:53
was fixed

**Closed as completed by Haehnchen** 2020-05-01 13:53 UTC
